### ISSUE TITLE
unable to compile on OS X Yosemite 10.10.5 or Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by dotcomputercraft** [gondor/depcon#10]
I keep getting the following error when I run 'go get -v github.com/gondor/depcon'

Error:
work/src/github.com/docker/libcompose/docker/container.go:478: undefined: parsers.ParseRepositoryTag
work/src/github.com/docker/libcompose/docker/container.go:480: undefined: "github.com/docker/docker/utils".ImageReference

I'm running on golang version 
ubuntu --> go version go1.5.2 linux/amd64
osX --> go version go1.5.2 darwin/amd64

How can i resolve these compile time issues?  Talk to you soon

Best Regards,

John Montoya

**Comment by gondor** [comment]
@dotcomputercraft, Our upstream decencies are using the new Vendor support in Go.  Try adding this env variable and try again.  You may want to clean you your $GOPATH/src/github.com/[gondor , docker ] if you still get errors.

```
$ export GO15VENDOREXPERIMENT=1
```

Let me know if that helps

**Comment by dotcomputercraft** [comment]
@gondor - Thank you, using the export variable enables a clean compile of the depcon module. Thanks again for open sourcing this project.  

Best Regards,
John Montoya

**Comment by gondor** [comment]
Awesome, thanks for letting me know this is resolved
